/*
 * Chisel: constraint graph and solver
 *
 * This is the layer that makes tangency stick. A tangent built here is not a
 * one-off construction that goes stale the moment you nudge a circle; it is a
 * record naming its drivers, and the solver regenerates its geometry from
 * whatever those drivers currently are.
 *
 * Two rules the whole design rests on:
 *
 *   Geometry is truth. Drivers are re-measured from their actual paths every
 *   solve, never read back from stored parameters. So resizing a circle with
 *   the plain selection tool, the scale tool, or Transform Each all work, and
 *   none of them had to know Chisel exists.
 *
 *   Rebuild, never patch. A dependent path is regenerated wholesale from its
 *   drivers. Nudging the existing points toward where they should be is how
 *   parametric systems accumulate drift and eventually produce garbage.
 *
 * Depends on: chisel.jsx, chisel-meta.jsx, chisel-tangency.jsx
 */

var CON = {};

CON.MAX_DEPTH = 8;      // dependency chain limit; also the cycle guard

//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// 1. Registry cache
//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

/*
 * Scanning every page item is the expensive part, and the panel wants to ask
 * "has anything moved?" several times a second. So the scan is cached and the
 * poll only reads geometricBounds off the items already found - four numbers
 * per constrained object, regardless of how big the document is.
 *
 * The cache is invalidated by any command that creates or destroys a record,
 * and by the document's page item count changing underneath us.
 */
CON.cache = null;

function conInvalidate() { CON.cache = null; }

function conRegistry(force) {
    var doc = app.activeDocument;
    var n = doc.pageItems.length;
    if (!force && CON.cache && CON.cache.doc === doc.name && CON.cache.n === n) {
        return CON.cache.reg;
    }
    var reg = metaScan(doc);
    CON.cache = { doc: doc.name, n: n, reg: reg };
    return reg;
}

/*
 * A cheap fingerprint of everything a constraint could depend on. Bounds are
 * rounded to a thousandth of a point: fine enough that a real nudge always
 * registers, coarse enough that Illustrator's float noise does not make the
 * solver fire on an idle document forever.
 *
 * Digested to a short token rather than returned raw. The panel round-trips
 * this string across the CEP bridge several times a second, so its size is not
 * free; and a raw hash carrying arbitrary punctuation is exactly the kind of
 * thing that collides with whatever separator the reply protocol picked.
 */
function conStateHash(reg) {
    var i, e, b, parts = [];
    for (i = 0; i < reg.list.length; i++) {
        e = reg.list[i];
        if (e.kind !== "circle" && e.kind !== "ref" && e.kind !== "anchor") { continue; }
        try { b = e.item.geometricBounds; } catch (err) { parts.push(e.id + ":gone"); continue; }
        parts.push(e.id + ":" +
            Math.round(b[0] * 1000) + "," + Math.round(b[1] * 1000) + "," +
            Math.round(b[2] * 1000) + "," + Math.round(b[3] * 1000));
    }
    parts.push("n=" + reg.count);
    return conDigest(parts.join("|"));
}

/*
 * Two FNV-1a passes with different seeds, concatenated. A collision means one
 * missed solve, corrected by the next change or by pressing Solve, so 64 bits
 * of a fast non-cryptographic hash is far more than this needs.
 */
function conDigest(s) {
    var h1 = 0x811c9dc5, h2 = 0x01000193, i, c;
    for (i = 0; i < s.length; i++) {
        c = s.charCodeAt(i);
        h1 = h1 ^ c;
        h1 = (h1 * 16777619) >>> 0;
        h2 = h2 ^ (c + i);
        h2 = (h2 * 2166136261) >>> 0;
    }
    return h1.toString(36) + "-" + h2.toString(36);
}

//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// 2. Registration
//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

/*
 * Tag a path as a constraint driver and return its ID.
 *
 * An object that already has an ID keeps it and keeps its kind. That second
 * part matters: a circle generated by a tangent-circle constraint is a
 * perfectly good driver for the next constraint, and an earlier version
 * stamped kind=circle over it, silently destroying the constraint that built
 * it. Only a bare reference is promoted.
 */
function conRegisterCircle(path) {
    var rec = metaRead(path);
    if (rec && rec.id) {
        if (rec.kind === "ref") {
            rec.kind = "circle";
            metaWrite(path, rec);
            conInvalidate();
        }
        return rec.id;
    }
    var id = metaNewId("c");
    metaPatch(path, { kind: "circle", id: id });
    conInvalidate();
    return id;
}

function conRegisterRef(path) {
    var rec = metaRead(path);
    if (rec && rec.id) { return rec.id; }
    var id = metaNewId("p");
    metaPatch(path, { kind: "ref", id: id });
    conInvalidate();
    return id;
}

/*
 * A container that can take a new sibling. Compound paths accept pathItems.add
 * but a new member would join the compound and inherit its even-odd fill, so
 * step out to the compound's own parent instead.
 */
function conContainerFor(item) {
    var p;
    try { p = item.parent; } catch (e) { return app.activeDocument; }
    try {
        if (p && p.typename === "CompoundPathItem") { return p.parent; }
    } catch (e2) {}
    return p || app.activeDocument;
}

function conNewPath(sibling, pts, closed) {
    var parent = conContainerFor(sibling);
    var p = parent.pathItems.add();
    writePath(p, pts, closed);
    if (typeof closed === "boolean") { p.closed = closed; }
    return p;
}

//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// 3. Per-kind rebuild
//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

/*
 * Resolve a driver reference to a live circle. Returns null when the driver was
 * deleted or has stopped being a circle, which the caller must treat as a
 * broken constraint rather than an error - deleting one of two circles is a
 * perfectly reasonable thing for a user to do.
 */
function conCircleOf(reg, id) {
    var e = metaGet(reg, id);
    if (!e || !metaAlive(e)) { return null; }
    var c;
    try { c = circleOfPath(e.item); } catch (err) { return null; }
    if (!c) { return null; }
    return c;
}

/* Rebuild one link. Returns "ok", "broken", or "impossible". */
function conSolveLink(reg, entry) {
    var rec = entry.rec;
    var A = conCircleOf(reg, rec.a);
    var B = conCircleOf(reg, rec.b);
    if (!A || !B) { return "broken"; }

    var crossed = metaB(rec, "crossed", false);
    var style = metaS(rec, "style", "belt");
    var side = metaN(rec, "side", 1);
    var pts = null, closed = true;

    if (style === "belt") {
        pts = beltOutline(A.c, A.r, B.c, B.r, crossed);
        closed = true;
    } else {
        pts = tangentSegment(A.c, A.r, B.c, B.r, crossed, side);
        closed = false;
    }
    if (!pts) { return "impossible"; }

    writePath(entry.item, pts, closed);
    return "ok";
}

/* Rebuild a circle that is defined as tangent to two others. */
function conSolveTanCircle(reg, entry) {
    var rec = entry.rec;
    var A = conCircleOf(reg, rec.a);
    var B = conCircleOf(reg, rec.b);
    if (!A || !B) { return "broken"; }

    var r = metaN(rec, "r", 50);
    var mode = metaS(rec, "mode", "ee");
    var pick = metaN(rec, "pick", 0);
    var sols = tangentCircle(A.c, A.r, B.c, B.r, r, mode);
    if (!sols.length) { return "impossible"; }
    var s = sols[pick] || sols[0];

    // Deliberately not writing the solved centre back into the record. It would
    // be a tag write on every solve, and the value is derived anyway.
    writePath(entry.item, arcPoints(s.c, s.r, 0, 0, true), true);
    return "ok";
}

/*
 * A tangent line running from a fixed anchor on another path to a circle. The
 * anchor is referenced by path ID and point index rather than copied, so
 * dragging that point drags the tangent with it.
 */
function conSolveTanLine(reg, entry) {
    var rec = entry.rec;
    var C = conCircleOf(reg, rec.a);
    if (!C) { return "broken"; }

    var origin = null;
    var src = metaGet(reg, metaS(rec, "from", ""));
    if (src && metaAlive(src)) {
        var pts = readPath(src.item);
        var idx = metaN(rec, "fromIndex", 0);
        if (idx >= 0 && idx < pts.length) { origin = pts[idx].a; }
    }
    if (!origin) { origin = [metaN(rec, "px", 0), metaN(rec, "py", 0)]; }

    var t = tangentsFromPoint(origin, C.c, C.r);
    if (!t.length) { return "impossible"; }
    var side = metaN(rec, "side", 1), i, hit = t[0];
    for (i = 0; i < t.length; i++) { if (t[i].side === side) { hit = t[i]; } }

    writePath(entry.item, linePoints(origin, hit.p), false);
    return "ok";
}

/*
 * Tangent continuity lock. The two handles at a locked anchor are forced
 * collinear on every solve, each keeping its own length, using the line from
 * the in handle to the out handle as the shared direction. That is exactly what
 * a smooth point means, and re-asserting it after every edit is what stops the
 * usual slow decay of a curve that was smooth when you drew it.
 */
function conSolveG1(entry) {
    var path = entry.item;
    var pts, idx, i, k, p, dir, lenL, lenR, nl, nr, changed = 0;
    try { pts = readPath(path); } catch (e) { return "broken"; }

    idx = metaSplitNums(metaS(entry.rec, "locks", ""));
    if (!idx.length) { return "ok"; }

    for (i = 0; i < idx.length; i++) {
        k = idx[i];
        if (k < 0 || k >= pts.length) { continue; }
        p = pts[k];
        lenL = vDist(p.a, p.l);
        lenR = vDist(p.a, p.r);
        if (lenL < 1e-9 && lenR < 1e-9) { continue; }

        dir = vSub(p.r, p.l);
        if (vLen(dir) < 1e-9) {
            // Both handles retracted onto one side: fall back to whichever
            // handle still has length, so the lock cannot invent a direction.
            dir = (lenR > lenL) ? vSub(p.r, p.a) : vSub(p.a, p.l);
        }
        if (vLen(dir) < 1e-9) { continue; }
        dir = vNorm(dir);

        nl = vSub(p.a, vMul(dir, lenL));
        nr = vAdd(p.a, vMul(dir, lenR));
        // Compare before assigning. A lock that is already satisfied must be a
        // true no-op, or the sync loop sees the rewrite as a change and solves
        // again on every tick.
        if (vDist(nl, p.l) < 1e-9 && vDist(nr, p.r) < 1e-9 && p.t === "s") { continue; }
        p.l = nl;
        p.r = nr;
        p.t = "s";
        changed++;
    }
    if (changed) { writePath(path, pts, path.closed); }
    return "ok";
}

/*
 * Weld: hold one anchor coincident with another on a different path, optionally
 * with matched tangent direction so the two paths read as one curve across the
 * join. The follower's handles move with its anchor rather than being reset, so
 * the shape of its own curve is preserved.
 *
 * The record lives on the follower - the path the solve actually rewrites -
 * alongside whatever else that path is. An earlier version parked it on a
 * hidden carrier path so that kinds stayed one-per-item; that put an invisible
 * object in the user's layers panel that they would eventually delete without
 * knowing what it was, which is a worse problem than a record with two roles.
 */
function conSolveWeld(reg, entry) {
    var rec = entry.rec;
    var foll = entry;
    var lead = metaGet(reg, metaS(rec, "weldTo", ""));
    if (!lead || !metaAlive(lead) || !metaAlive(foll)) { return "broken"; }

    var li = metaN(rec, "weldTheirs", 0), fi = metaN(rec, "weldMine", 0);
    var lp, fp;
    try { lp = readPath(lead.item); fp = readPath(foll.item); } catch (e) { return "broken"; }
    if (li < 0 || li >= lp.length || fi < 0 || fi >= fp.length) { return "broken"; }

    var L = lp[li], F = fp[fi], moved = false, k;
    var d = vSub(L.a, F.a);
    if (vLen(d) > 1e-9) {
        /*
         * Two useful readings of "keep these together", and they are not the
         * same operation:
         *
         *   shape  - translate the whole follower, so two objects stay locked
         *            in formation. This is what people mean when they say lock
         *            these shapes together.
         *   point  - move only the welded anchor, so the follower stretches to
         *            stay attached. This is what you want for joining the end
         *            of one open path to another.
         */
        if (metaS(rec, "weldMode", "shape") === "point") {
            F.a = vAdd(F.a, d);
            F.l = vAdd(F.l, d);
            F.r = vAdd(F.r, d);
        } else {
            for (k = 0; k < fp.length; k++) {
                fp[k].a = vAdd(fp[k].a, d);
                fp[k].l = vAdd(fp[k].l, d);
                fp[k].r = vAdd(fp[k].r, d);
            }
        }
        moved = true;
    }

    if (metaB(rec, "weldG1", false)) {
        // The leader's live handle at the join sets the direction; the follower
        // opposes it, keeping its own handle lengths.
        var ldir = vSub(L.a, L.l);
        if (vLen(ldir) < 1e-9) { ldir = vSub(L.r, L.a); }
        if (vLen(ldir) > 1e-9) {
            ldir = vNorm(ldir);
            var fl = vDist(F.a, F.l), fr = vDist(F.a, F.r);
            var nl = vSub(F.a, vMul(ldir, fl));
            var nr = vAdd(F.a, vMul(ldir, fr));
            if (vDist(nl, F.l) > 1e-9 || vDist(nr, F.r) > 1e-9) {
                F.l = nl;
                F.r = nr;
                F.t = "s";
                moved = true;
            }
        }
    }
    // Only write when something actually changed. A no-op writePath still
    // perturbs the geometry enough to move the change hash, and the sync loop
    // would then re-solve on every tick forever.
    if (moved) { writePath(foll.item, fp, foll.item.closed); }
    return "ok";
}

//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// 4. The solve pass
//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

/*
 * Dependency depth, so a tangent circle built on two circles can itself drive
 * another tangent. Depth is computed by walking driver references upward with a
 * hard ceiling, which doubles as the cycle guard: a constraint that reaches
 * MAX_DEPTH is either genuinely that deep or circular, and either way solving
 * it in that order is the best available answer.
 */
function conDepth(reg, entry, seen) {
    if (!seen) { seen = {}; }
    if (seen[entry.id]) { return CON.MAX_DEPTH; }
    seen[entry.id] = true;

    var refs = [entry.rec.a, entry.rec.b, entry.rec.from, entry.rec.weldTo], i, e, d, best = 0;
    for (i = 0; i < refs.length; i++) {
        if (!refs[i]) { continue; }
        e = metaGet(reg, refs[i]);
        if (!e || e.kind === "circle" || e.kind === "ref") { continue; }
        d = 1 + conDepth(reg, e, seen);
        if (d > best) { best = d; }
        if (best >= CON.MAX_DEPTH) { return CON.MAX_DEPTH; }
    }
    return best;
}

function conSortByDepth(reg, entries) {
    var i, j, tmp;
    for (i = 0; i < entries.length; i++) { entries[i].depth = conDepth(reg, entries[i], null); }
    for (i = 1; i < entries.length; i++) {          // insertion sort; ES3, tiny n
        tmp = entries[i];
        j = i - 1;
        while (j >= 0 && entries[j].depth > tmp.depth) { entries[j + 1] = entries[j]; j--; }
        entries[j + 1] = tmp;
    }
    return entries;
}

/*
 * Solve everything. Returns a tally rather than throwing, because one broken
 * constraint in a document of fifty must not stop the other forty-nine from
 * updating.
 */
/*
 * A record can carry more than one role: the same path can be a tangent link,
 * hold tangent locks on its own anchors, and be welded to a neighbour. So the
 * pass runs in three waves rather than switching on a single kind.
 *
 * Order matters. Generated geometry first, because a weld may be attaching to a
 * point that is about to move. Welds next, since they relocate anchors. Tangent
 * locks last, so they get the final word on handle direction.
 */
function conSolveAll(force) {
    var reg = conRegistry(force);
    var gen = [], welds = [], locks = [], i, e, r;
    for (i = 0; i < reg.list.length; i++) {
        e = reg.list[i];
        if (e.kind === "tanlink" || e.kind === "tancircle" || e.kind === "tanline") { gen.push(e); }
        if (e.rec.weldTo) { welds.push(e); }
        if (e.rec.locks) { locks.push(e); }
    }
    conSortByDepth(reg, gen);
    conSortByDepth(reg, welds);

    var okN = 0, broken = 0, impossible = 0;

    function tally(res) {
        if (res === "ok") { okN++; }
        else if (res === "impossible") { impossible++; }
        else { broken++; }
    }

    for (i = 0; i < gen.length; i++) {
        e = gen[i];
        r = "ok";
        try {
            if (e.kind === "tanlink") { r = conSolveLink(reg, e); }
            else if (e.kind === "tancircle") { r = conSolveTanCircle(reg, e); }
            else if (e.kind === "tanline") { r = conSolveTanLine(reg, e); }
        } catch (err) { r = "broken"; }
        tally(r);
    }
    for (i = 0; i < welds.length; i++) {
        try { tally(conSolveWeld(reg, welds[i])); } catch (err2) { tally("broken"); }
    }
    for (i = 0; i < locks.length; i++) {
        try { tally(conSolveG1(locks[i])); } catch (err3) { tally("broken"); }
    }

    return {
        total: gen.length + welds.length + locks.length,
        ok: okN, broken: broken, impossible: impossible, reg: reg
    };
}

//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// 5. Commands
//= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

/*
 * The headline operation: take two circles and join them along their common
 * tangents, locked. Style "belt" gives the single closed pulley outline;
 * "lines" gives the two straight tangents as separate paths; "line" gives one.
 */
CMD.tanConnect = function (o) {
    var got = twoCircles();
    if (got.err) { return got.err; }

    var style = chStr(o.style, "belt");
    var crossed = chBool(o.crossed, false);
    var idA = conRegisterCircle(got.pathA);
    var idB = conRegisterCircle(got.pathB);

    var made = [], sides, i, side, pts, np;

    if (style === "belt") {
        pts = beltOutline(got.A.c, got.A.r, got.B.c, got.B.r, crossed);
        if (!pts) {
            return crossed
                ? "These circles overlap, so they have no crossed tangent. Move them apart or use the open belt."
                : "One circle is entirely inside the other, so they share no tangent.";
        }
        np = conNewPath(got.pathA, pts, true);
        styleFrom(np, got.pathA, true);
        metaWrite(np, { kind: "tanlink", id: metaNewId("t"), a: idA, b: idB, style: "belt", crossed: crossed });
        made.push(np);
    } else {
        sides = (style === "line") ? [chNum(o.side, 1)] : [1, -1];
        for (i = 0; i < sides.length; i++) {
            side = sides[i];
            pts = tangentSegment(got.A.c, got.A.r, got.B.c, got.B.r, crossed, side);
            if (!pts) { continue; }
            np = conNewPath(got.pathA, pts, false);
            styleFrom(np, got.pathA, false);
            metaWrite(np, { kind: "tanlink", id: metaNewId("t"), a: idA, b: idB, style: "line", crossed: crossed, side: side });
            made.push(np);
        }
        if (!made.length) {
            return crossed
                ? "These circles overlap, so they have no crossed tangent."
                : "One circle is entirely inside the other, so they share no tangent.";
        }
    }

    conInvalidate();
    app.activeDocument.selection = made;
    return "Locked " + made.length + " " + (style === "belt" ? "belt" : "tangent") +
           (made.length === 1 ? "" : "s") + " to both circles. Move or scale either circle and it follows.";
};

/* A new circle of a given radius, tangent to the two selected circles. */
CMD.tanCircleAdd = function (o) {
    var got = twoCircles();
    if (got.err) { return got.err; }

    var r = chNum(o.radius, 50);
    if (r <= 0) { return "Radius must be greater than zero."; }
    var mode = chStr(o.mode, "ee");
    var pick = chNum(o.pick, 0);

    var sols = tangentCircle(got.A.c, got.A.r, got.B.c, got.B.r, r, mode);
    if (!sols.length) {
        return "No circle of radius " + r + " can touch both. Try a larger radius, or a different inside/outside mode.";
    }
    var s = sols[pick] || sols[0];

    var idA = conRegisterCircle(got.pathA);
    var idB = conRegisterCircle(got.pathB);
    var np = conNewPath(got.pathA, arcPoints(s.c, s.r, 0, 0, true), true);
    styleFrom(np, got.pathA, false);
    metaWrite(np, {
        kind: "tancircle", id: metaNewId("k"), a: idA, b: idB,
        r: r, mode: mode, pick: pick, cx: s.c[0], cy: s.c[1]
    });

    conInvalidate();
    app.activeDocument.selection = [np];
    return "Tangent circle placed and locked to both drivers.";
};

/*
 * Tangent from a selected anchor to a circle. Select the circle and a path with
 * exactly one anchor selected; the line stays attached to that anchor.
 */
CMD.tanFromPoint = function (o) {
    var paths = selectedPaths();
    if (paths.length !== 2) { return "Select a circle, plus one path with a single anchor selected."; }

    var i, c, circlePathIdx = -1;
    for (i = 0; i < 2; i++) {
        c = circleOfPath(paths[i]);
        if (c && c.ok) { circlePathIdx = i; break; }
    }
    if (circlePathIdx < 0) { return "Neither selected path is a circle."; }

    var circPath = paths[circlePathIdx];
    var srcPath = paths[1 - circlePathIdx];
    var C = circleOfPath(circPath);

    var pts = readPath(srcPath), idx = -1, n = 0;
    for (i = 0; i < pts.length; i++) { if (pts[i].sel) { idx = i; n++; } }
    if (n !== 1) { return "Select exactly one anchor on the other path. Found " + n + "."; }

    var origin = pts[idx].a;
    var t = tangentsFromPoint(origin, C.c, C.r);
    if (!t.length) { return "That point is inside the circle, so it has no tangent to it."; }

    var side = chNum(o.side, 1), hit = t[0];
    for (i = 0; i < t.length; i++) { if (t[i].side === side) { hit = t[i]; } }

    var idC = conRegisterCircle(circPath);
    var idS = conRegisterRef(srcPath);
    var np = conNewPath(circPath, linePoints(origin, hit.p), false);
    styleFrom(np, circPath, false);
    metaWrite(np, {
        kind: "tanline", id: metaNewId("l"), a: idC, from: idS, fromIndex: idx,
        side: side, px: origin[0], py: origin[1]
    });

    conInvalidate();
    app.activeDocument.selection = [np];
    return "Tangent locked to the circle and to anchor " + (idx + 1) + ".";
};

/* Lock the selected anchors to tangent continuity. */
CMD.lockTangent = function () {
    var paths = selectedPaths(), i, j, pts, idx, rec, nPts = 0, nPaths = 0;
    if (!paths.length) { return "Select the anchors to lock."; }

    for (i = 0; i < paths.length; i++) {
        pts = readPath(paths[i]);
        idx = [];
        for (j = 0; j < pts.length; j++) { if (pts[j].sel) { idx.push(j); } }
        if (!idx.length) { continue; }

        rec = metaRead(paths[i]) || {};
        if (!rec.kind) { rec.kind = "ref"; }
        if (!rec.id) { rec.id = metaNewId("g"); }
        rec.locks = metaJoinNums(conMergeLocks(metaSplitNums(metaS(rec, "locks", "")), idx));
        metaWrite(paths[i], rec);
        nPts += idx.length;
        nPaths++;
    }
    if (!nPts) { return "No anchors selected. Use the Direct Selection tool first."; }

    conInvalidate();
    conSolveAll(true);
    return "Locked " + nPts + " anchor" + (nPts === 1 ? "" : "s") + " across " + nPaths +
           " path" + (nPaths === 1 ? "" : "s") + " to tangent continuity.";
};

function conMergeLocks(existing, add) {
    var out = [], seen = {}, i;
    for (i = 0; i < existing.length; i++) {
        if (!seen[existing[i]]) { seen[existing[i]] = true; out.push(existing[i]); }
    }
    for (i = 0; i < add.length; i++) {
        if (!seen[add[i]]) { seen[add[i]] = true; out.push(add[i]); }
    }
    return out;
}

/*
 * With anchors selected, release just those. With only whole objects selected,
 * release every lock on them. Only the locks field is touched: a path that is
 * also a tangent link keeps being one.
 */
CMD.unlockTangent = function () {
    var paths = selectedPaths(), i, j, pts, rec, locks, keep, n = 0, anySel;
    for (i = 0; i < paths.length; i++) {
        rec = metaRead(paths[i]);
        if (!rec || !rec.locks) { continue; }
        pts = readPath(paths[i]);
        locks = metaSplitNums(metaS(rec, "locks", ""));
        anySel = false;
        for (j = 0; j < pts.length; j++) { if (pts[j].sel) { anySel = true; break; } }

        keep = [];
        for (j = 0; j < locks.length; j++) {
            if (!anySel || (locks[j] >= 0 && locks[j] < pts.length && pts[locks[j]].sel)) { n++; }
            else { keep.push(locks[j]); }
        }
        if (keep.length) { rec.locks = metaJoinNums(keep); }
        else { delete rec.locks; }
        metaWrite(paths[i], rec);
    }
    conInvalidate();
    return n ? ("Released " + n + " tangent lock" + (n === 1 ? "" : "s") + ".")
             : "Nothing locked in the selection.";
};

/*
 * Weld two anchors on two different paths. The first selected path leads; the
 * second follows it. g1 also matches the tangent direction across the join.
 */
CMD.weldPoints = function (o) {
    var paths = selectedPaths();
    if (paths.length !== 2) { return "Select two paths with one anchor selected on each."; }

    var a = readPath(paths[0]), b = readPath(paths[1]);
    var ai = conSoleSelected(a), bi = conSoleSelected(b);
    if (ai < 0) { return "Select exactly one anchor on the first path."; }
    if (bi < 0) { return "Select exactly one anchor on the second path."; }

    var idA = conRegisterRef(paths[0]);
    conRegisterRef(paths[1]);

    // The record lives on the follower, because that is the path the solve
    // rewrites, and it merges into whatever role that path already has.
    var g1 = chBool(o.g1, true);
    var mode = chStr(o.mode, "shape");
    var rec = metaRead(paths[1]) || { kind: "ref", id: metaNewId("w") };
    rec.weldTo = idA;
    rec.weldTheirs = ai;
    rec.weldMine = bi;
    rec.weldG1 = g1;
    rec.weldMode = mode;
    metaWrite(paths[1], rec);

    conInvalidate();
    conSolveAll(true);
    return "Welded anchor " + (bi + 1) + " to anchor " + (ai + 1) +
           (g1 ? " with matched tangents. " : ". ") +
           (mode === "point" ? "Only that anchor follows." : "The whole second path follows.");
};

/* Break the weld on the selected paths, leaving the geometry where it is. */
CMD.unweld = function () {
    var paths = selectedPaths(), i, rec, n = 0;
    for (i = 0; i < paths.length; i++) {
        rec = metaRead(paths[i]);
        if (!rec || !rec.weldTo) { continue; }
        delete rec.weldTo;
        delete rec.weldTheirs;
        delete rec.weldMine;
        delete rec.weldG1;
        delete rec.weldMode;
        metaWrite(paths[i], rec);
        n++;
    }
    conInvalidate();
    return n ? ("Broke " + n + " weld" + (n === 1 ? "" : "s") + ".") : "Nothing welded in the selection.";
};

function conSoleSelected(pts) {
    var i, idx = -1, n = 0;
    for (i = 0; i < pts.length; i++) { if (pts[i].sel) { idx = i; n++; } }
    return (n === 1) ? idx : -1;
}

/* Re-solve everything now. */
CMD.solveAll = function () {
    var r = conSolveAll(true);
    if (!r.total) { return "Nothing is locked in this document."; }
    var msg = "Solved " + r.ok + " of " + r.total + ".";
    if (r.impossible) { msg += " " + r.impossible + " cannot be built at the current positions."; }
    if (r.broken) { msg += " " + r.broken + " lost a driver."; }
    return msg;
};

/*
 * The auto-sync probe. Returns "hash|count" and, when the hash has moved since
 * the caller last saw it, re-solves first. Keeping the compare on this side of
 * the bridge means the panel does one small evalScript per tick instead of
 * pulling the whole document state across.
 */
CMD.syncProbe = function (o) {
    var reg = conRegistry(false);
    if (!reg.links.length && !conHasLocks(reg)) { return "idle|0|0"; }

    var h = conStateHash(reg);
    var prev = chStr(o.hash, "");
    if (h === prev) { return "same|" + reg.count + "|0"; }

    var r = conSolveAll(false);
    // Solving moves dependent geometry, so the post-solve hash is the one to
    // compare against next tick. Without this the loop re-solves forever.
    var h2 = conStateHash(conRegistry(false));
    return "solved|" + r.ok + "|" + r.broken + "|" + h2;
};

function conHasLocks(reg) {
    var i;
    for (i = 0; i < reg.list.length; i++) {
        if (reg.list[i].rec.locks || reg.list[i].rec.weldTo) { return true; }
    }
    return false;
}

/* Current hash without solving, for the panel's first tick. */
CMD.syncHash = function () {
    return conStateHash(conRegistry(true));
};

/* Drop the constraint records on the selection, leaving ordinary artwork. */
CMD.releaseSelection = function () {
    var paths = selectedPaths(), i, n = 0;
    for (i = 0; i < paths.length; i++) {
        if (metaClear(paths[i])) { n++; }
    }
    conInvalidate();
    return n ? ("Released " + n + " object" + (n === 1 ? "" : "s") + ". They are plain paths now.")
             : "Nothing in the selection was locked.";
};

/* Select whatever drives the current selection, so you can see the chain. */
CMD.selectDrivers = function () {
    var reg = conRegistry(true);
    var paths = selectedPaths(), i, rec, out = [], e, refs, j;
    for (i = 0; i < paths.length; i++) {
        rec = metaRead(paths[i]);
        if (!rec) { continue; }
        refs = [rec.a, rec.b, rec.from];
        for (j = 0; j < refs.length; j++) {
            if (!refs[j]) { continue; }
            e = metaGet(reg, refs[j]);
            if (e && metaAlive(e)) { out.push(e.item); }
        }
    }
    if (!out.length) { return "The selection has no drivers."; }
    app.activeDocument.selection = out;
    return "Selected " + out.length + " driver" + (out.length === 1 ? "" : "s") + ".";
};

/* Panel readout: what is locked in this document, and is any of it broken. */
CMD.constraintsInfo = function () {
    var reg = conRegistry(true);
    var i, e, links = 0, circles = 0, locks = 0, welds = 0, broken = 0;
    for (i = 0; i < reg.list.length; i++) {
        e = reg.list[i];
        if (e.kind === "tanlink" || e.kind === "tanline" || e.kind === "tancircle") {
            links++;
            if (!conCircleOf(reg, e.rec.a) || (e.rec.b && !conCircleOf(reg, e.rec.b))) { broken++; }
        } else if (e.kind === "circle") { circles++; }
        if (e.rec.locks) { locks += metaSplitNums(metaS(e.rec, "locks", "")).length; }
        if (e.rec.weldTo) {
            welds++;
            if (!metaGet(reg, e.rec.weldTo)) { broken++; }
        }
    }
    return links + "|" + circles + "|" + locks + "|" + welds + "|" + broken;
};
